version: 2

build: &BUILD
  steps:
    - checkout
    - run: yarn install
    - run: yarn build
    - run: yarn test
    - run: yarn codecov-report

jobs:
  dubnium:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:10
  erbium:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:12
  fermium:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node:14
  latest:
    <<: *BUILD
    working_directory: ~/gtg
    docker:
      - image: circleci/node
  stryker:
    working_directory: ~/gtg
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn stryker
      - store_artifacts:
          path: packages/generic-type-guard/reports/mutation/html
          destination: stryker-generic-type-guard

workflows:
  version: 2
  ci:
    jobs:
      - dubnium:
          requires: ["fermium"]
      - erbium:
          requires: ["fermium"]
      - fermium
      - latest:
          requires: ["fermium"]
      - stryker:
          requires: ["fermium"]
